name: Test E2E Suites
on: 
  workflow_dispatch:
    inputs:
      browser: 
        description: "Select a browser"
        required: true
        default: chrome
        type: choice
        options:
        - chrome
        - firefox
        - safari
  
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test script run
        run: echo "Hello world"