name: Test E2E Suites
on: 
  workflow_dispatch:
    inputs:
      suite:
        description: "Select a E2E workflow to run"
        required: true
        default: loginWorkflow
        type: choice
        options:
        - loginWorkflow

      browser: 
        description: "Select a browser"
        required: true
        default: chromium
        type: choice
        options:
        - chromium
        - firefox
        - safari
  
jobs:
  E2E Workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps ${{ inputs.browser }}

      - name: Run selected suite
        run: npx playwright test ${{ inputs.suite }}.spec.ts --project=${{ inputs.browser }}